<?php /* @var this MageProfis_CustomerNotice_Block_Notice */ ?>
<?php $notices = $this->getCurrentViewNotices(); ?>
<?php if (count($notices) > 0): ?>
    <?php $notice = $notices[0]; ?>
        <?php Zend_Debug::dump($notice); ?>
    <div class="modal fade" id="customerNoticeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <div class="modal-title"><?php echo $notice->getTitle(); ?></div>
                </div>
                <div class="modal-body std">
                    <?php echo $this->getNoticeContent($notice); ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery('#customerNoticeModal').modal();
    });
</script>